! WIP ! upgrade gateway civic
credix-finance/credix-app pull request #114
Opened 2022-01-11 09:09 UTC by BouweCeunen

2022-01-11 11:20 UTC, SushantChandla approved these changes, later dismissed

2022-01-20 16:34 UTC, RuvendeGroote requested changes

2022-01-20 16:34 UTC, RuvenSalamon commented on package.json
> +    "@civic/solana-gateway-react": "^0.4.9",
we can try using 0.4.10 because that release happened at the same time as the rust crate release we use

2022-01-24 09:50 UTC, SushantChandla approved these changes

2022-01-24 13:03 UTC, RuvenSalamon approved these changes

2022-01-24 13:03 UTC, merged